# `cmd+b r` reloads config
bind r source-file ~/.config/tmux/tmux.conf \; display "Tmux config reloaded."

# Delay for vim compatibility
set -sg escape-time 10

# Colors
set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ',screen-256color:RGB'

# Scroll buffer
set -g history-limit 100000

# Scrolling with mouse
setw -g mouse off

# `hjkl` navigation
setw -g mode-keys vi

